# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer overview indent
#+LANGUAGE: pt-br
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export

#+TITLE: Dynamic Load Balancing and Scalability Analysis of the Mandelbrot Set in a Multi-Threaded HPC Application
#+LATEX: \makeatletter \def\beamer@shorttitle{Analysis of the Mandelbrot Set in an HPC Application} \makeatother
#+SUBTITLE: SSCAD-WIC 2025
#+AUTHOR: Francisco Etcheverria, Rayan Raddatz, Kenichi Brumati, Lucas Mello Schnorr
#+DATE: 28/10/2025

#+LATEX_CLASS: beamer
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \def\input@path{{theme/}}
#+LATEX_HEADER: \makeatother
#+BEAMER_THEME:Inf
#+LATEX_CLASS_OPTIONS: [xcolor=dvipsnames,10pt,aspectratio=169]
#+OPTIONS: H:2 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t

#+LATEX_HEADER: \graphicspath{{theme/}{../figures/}{figures/}}

* Introdução

** Roteiro

#+LATEX: \tableofcontents

** Conjunto de Mandelbrot

O conjunto de Mandelbrot \cite{mandelbrot1980} é um conjunto definido pelos pontos complexos \( c \) para os quais a sequência

\[
z_{n+1} = z_n^2 + c, \quad z_0 = 0
\]

permanece limitada, ou seja, não diverge para o infinito após um número finito de iterações.

** Visualização do conjunto

- Cada pixel é associado a um ponto do plano complexo. 
- Cores são atribuídas de acordo com o número de iterações até a sequência divergir.

#+LATEX: \vfill\pause

#+LATEX: \begin{columns}
#+LATEX: \column{0.49\textwidth}
#+LATEX: \includegraphics[width=\linewidth]{figures/frac1.png}
#+LATEX: \column{0.49\textwidth}
#+LATEX: \includegraphics[width=\linewidth]{figures/frac2.png}
#+LATEX: \end{columns}

#+LATEX: \vfill

As imagens resultantes tem uma estrutura fractal, com detalhe infinito sendo encontrado ao ampliar a imagem.

** Aspectos computacionais

- O conjunto de Mandelbrot é *trivialmente paralelizável*: Cada pixel pode ser computado independentemente.
- Diferentes regiões da imagem requerem números de iterações diferentes.
- Logo, o *balanceamento de carga* é importante para se obter performance máxima.

** Trabalhos Relacionados

O *balanceamento de carga* é amplamente estudado em sistemas paralelos e de alto desempenho, 
e o conjunto de Mandelbrot é frequentemente utilizado neste contexto.

- *\cite{gomez2020mpi}* compara abordagens utilizando MPI e OpenMP no cálculo do conjunto, assim como abordagens de distribuição de trabalho estáticas e dinâmicas.
- *\cite{mohammed2020two}* propõe uma abordagem de balanceamento dinâmico em dois níveis com MPI e OpenMP, e utiliza o Conjunto de Mandelbrot como um /benchmark/.

#+LATEX: \pause\vfill

Nosso trabalho utiliza uma arquitetura cliente-servidor que aloca o trabalho dinamicamente. 
Realizamos um conjunto de experimentos para avaliar sua eficiência e escalabilidade, e investigar como o 
balanceamento de carga se comporta em diferentes cenários.

* Materiais e Métodos

** Arquitetura do sistema: Overview

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.55\textwidth :center
[[../figures/system_architecture.pdf]]
#+END_CENTER

#+LATEX: \vfill

- *Cliente*: Recebe input do usuário, solicita ao servidor o cálculo de regiões, recebe respostas e renderiza o fractal.
- *Servidor*: O coordenador recebe pedidos do cliente, divide-os em tarefas menores e distribui a carga de trabalho entre seus /workers/. 

** Arquitetura do sistema: /payloads/ e /responses/

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.55\textwidth :center
[[../figures/system_architecture.pdf]]  
#+END_CENTER

#+LATEX: \vfill

- A interação ocorre através da troca de /payloads/ e /responses/.
- */Payloads/* contêm os limites da região, dimensões da tela, o número máximo de iterações, e a granularidade - o tamanho em pixels dos blocos em que o trabalho é dividido.
- */Responses/* contêm os valores calculados pelo servidor, o payload de origem e o identificador do worker que os produziu.

** Arquitetura do sistema: Fluxo de comunicação

#+BEGIN_CENTER
#+ATTR_LATEX: :width 0.55\textwidth :center
[[../figures/system_architecture.pdf]]
#+END_CENTER

#+LATEX: \vfill

- O coordenador recebe um /payload/, divide em vários menores e os distribui aos *workers* dinamicamente.
- Os /workers/ pedem trabalho para o coordenador, enviando os resultados assim que são calculados.
- Cada /response/ é redirecionado ao cliente, permitindo visualização progressiva da imagem. 

** Configuração de hardware

Os experimentos foram executados no Parque Computacional de Alto Desempenho (PCAD) do Instituto de Informática da UFRGS.

#+LATEX: \vfill

O cliente rodou em uma máquina *draco*, com:

- 2x Intel Xeon E5-2640 v2 @ 2.00GHz, 32 cores
- 64GB DDR4

O servidor rodou em até seis máquinas *cei*, cada um com:

- 2x Intel Xeon Silver 4116 @ 2.10GHz, 24 cores por nó
- 96GB DDR4

** Projeto Experimental

- Resolução: 1920\times1080

#+LATEX: \pause

- Granularidade: [5\times5, 10\times10, 20\times20, 40\times40, 60\times60, 120\times120]

#+LATEX: \pause

- Quantidade de nós do servidor: 1 a 6 nós (24 a 144 ranks MPI)

#+LATEX: \pause

- Região do fractal e número de iterações máximo: *easy* estressa o /overhead/ de comunicação, *default* é um caso desbalanceado típico, e *hard* testa a vazão computacional do sistema

#+LATEX: \vfill

#+LATEX: \begin{columns}
#+LATEX: \column{0.33\textwidth}
#+LATEX: \includegraphics[width=\linewidth]{../figures/region_easy.png}
#+LATEX: \centering\footnotesize easy (máx. 1024 it.)
#+LATEX: \column{0.33\textwidth}
#+LATEX: \includegraphics[width=\linewidth]{../figures/region_default.png}
#+LATEX: \centering\footnotesize default (máx. 150000 it.)
#+LATEX: \column{0.33\textwidth}
#+LATEX: \includegraphics[width=\linewidth]{../figures/region_hard.png}
#+LATEX: \centering\footnotesize hard (máx. 300000 it.)
#+LATEX: \end{columns}

#+LATEX: \vfill\pause

- 5 repetições de cada configuração

* Resultados

** Métricas

** Resultados 1

** Resultados 2

** Resultados 3

* Conclusão

** Considerações finais

** Trabalhos futuros

** Referências

#+LATEX: \bibliographystyle{sbc}
#+LATEX: \bibliography{refs} 

* Bib file                                                         :noexport:
#+begin_src bibtex :tangle refs.bib

@article{gomez2020mpi,
  title={MPI vs OpenMP: A case study on parallel generation of Mandelbrot set},
  author={G{\'o}mez, Ernesto Soto},
  journal={Innovation and Software},
  volume={1},
  number={2},
  pages={12--26},
  year={2020}
}

@inproceedings{mohammed2020two,
  title={Two-level dynamic load balancing for high performance scientific applications},
  author={Mohammed, Ali and Cavelan, Aur{\'e}lien and Ciorba, Florina M and Cabez{\'o}n, Rub{\'e}n M and Banicescu, Ioana},
  booktitle={SIAM Conference on Parallel Processing for Scientific Computing},
  year={2020},
}

@article{mandelbrot1980,
  author = {Mandelbrot, Benoit B.},
  title = { “Fractal Aspects of the Iteration of Z → z $\Lambda$(1-Z) for Complex $\Lambda$ and Z”},
  journal = {Annals of the New York Academy of Sciences},
  volume = {357},
  number = {1},
  pages = {249-259},
  year = {1980}
}
#+end_src
